### ISSUE TITLE
Shipment::downloadLabel($type) returns GeneralApiException (404)

### ISSUE THREAD

**Issue by JSRM99** [Trunkrs/Trunkrs-SDK-PHP#33]
**Trunkrs SDK version(s) affected**: 2.1.2
**PHP version(s) affected**: 7.3.11

**Description**  
Whent trying to call the `downloadLabel()` function on a `Shipment` class it returns a `GeneralApiException`.
Exception returned:
![image](https://user-images.githubusercontent.com/37828702/108681573-96be6d00-74ef-11eb-9236-21ff2d324680.png)

**How to reproduce**  
```php
$trunkrsShipment = TrunkrsShipment::find($id);
$trunkrsShipment->downloadLabel('pdf');
```
Contents  of `$trunkrsShipment`:
![image](https://user-images.githubusercontent.com/37828702/108681841-ec931500-74ef-11eb-953d-02fed19b2d9e.png)

**Additional context**  
Tested against the Staging API.

**Comment by fean** [comment]
Hey Juup!

This is a deprecated feature and will only work against the V1 API. I will add some extra documentation and a clear error when calling this on API V2.

Thanks for notifying us of this problem!

**Comment by JSRM99** [comment]
Hi @fean,

How do we go about downloading a label in the V2 version of the SDK then?
Or is this not possible at all with the new SDK?

-Juup

**Comment by fean** [comment]
Ah, I see what you mean. I wrongly assumed that the label urls were not secured. This was the case in V1, sadly this part of our API is not all too well documented. My apologies for the inconvenience!

I will add a new `download($type)` method to the `LabelUrls`, so that `$shipment->label->download($type)` becomes possible. You can expect a new release within two hours.
